services:
  websocket-server:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MAX_MESSAGES_PER_MINUTE=60
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge